{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.tmslpm",
    "module": "gradle-include-properties",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-include-properties-1.0.0.jar",
          "url": "gradle-include-properties-1.0.0.jar",
          "size": 8983,
          "sha512": "d9ef6cf2591941a20ab55d8036b81b7b54ba6b0b4bdbaec9137cf260a47c0bbe513c1335502b6f84ad952b3f22a77dfb6c8af457edcf083f275fd239fc8b4233",
          "sha256": "e87e9f24017de2f7d1c09a5a382b303b20a2d1db4ac593e2c93877df06cfa601",
          "sha1": "c41f095c72ad240eaa46781ff5d6e3bdd136f5d8",
          "md5": "f73caabfe4e46561d9427f052625ec37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-include-properties-1.0.0.jar",
          "url": "gradle-include-properties-1.0.0.jar",
          "size": 8983,
          "sha512": "d9ef6cf2591941a20ab55d8036b81b7b54ba6b0b4bdbaec9137cf260a47c0bbe513c1335502b6f84ad952b3f22a77dfb6c8af457edcf083f275fd239fc8b4233",
          "sha256": "e87e9f24017de2f7d1c09a5a382b303b20a2d1db4ac593e2c93877df06cfa601",
          "sha1": "c41f095c72ad240eaa46781ff5d6e3bdd136f5d8",
          "md5": "f73caabfe4e46561d9427f052625ec37"
        }
      ]
    }
  ]
}
